import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/src/components/layout/navbar/Navbar";
import { Plus_Jakarta_Sans, Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus-jakarta-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body 
      className={`${plusJakartaSans.variable} font-plus-jakarta-sans bg-gray-100 min-h-screen`}>
        <Navbar />
        {children}
        </body>
    </html>
  );
}
